var GAME_LEVELS = [
  ["                                                                                 ",
   "                                                                                ",
   "                                                                                ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x    xxxxxx  xxxxxx  x                                                     x  ",
   "  x    x       x    x  x                                                     x  ",
   "  x    x  xxx  x    x  x                                                     x  ",
   "  x    x    x  x    x                                                        x  ",
   "  x    xxxxxx  xxxxxx  x                                                     x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                 o                        x  ",   
   "  x                                     o o       xxxxx                      x  ",
   "  x                           o        xxxxx      !!!!!                      x  ",
   "  x   @                     xxxxx      !!!!!        v                      o x  ",
   "  x                         !!!!!        v                                 o x  ",
   "  x  eee                      v                                            o x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxx                          xxxxxx    xxxxxxxxxxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxx                          xxxxxx   =xxxxxxxxxxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx!!!!xxxxxxxxxxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx!!!!xxxxxxxxxxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                "],
    
  
  ["                                                                                                                  ",
   "                                                              x                                                   ",
   "                                                              x                                                o  ",
   "                                                              x                                                o  ",
   "                                                              x                                                o  ",
   "                                                              x                                              =xxxx",
   "                                                              x=                                                  ",
   "                                                              x                                                  =",
   "                                                              x=                xxxx                      o       ",
   "                                                                                                                  ",
   "                                                                        o                                         ",
   "                                                                                              o                   ",
   "                                                                                                                  ",
   "                                   !!!   o                            xxxx                            xxxx        ",
   "       x                  o  xxxx  !x!                                                                            ",
   "       x=                          !x!  xxxx                                              xxxx                    ",
   "       x                          =!x!                                                                            ",
   "       x=                          !!!                                                                            ",
   "                       xxxx                       o                                                               ",
   "                                                  o                                                               ",
   "                o                                 o                                                               ",
   "              xxxx                                o               o                                               ",
   "                                                  o             xxxx                                              ",
   "                                                  o                                                               ",
   "           o                                                                                                      ",
   "         xxxx                                                                                                     ",
   "                                                                                                                  ",
   "   @                                              q                                                               ",
   "   eee                                         xxxxxxxx                                                           ",
   "xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                                  "],
   
   
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                             xxx                                                                                  ",
   "@                                                                                                                ",
   "eee                                                                                                               ",
   "xxx                                                                                                               ",
   "xxx                                                                                                               ",
   "xxx                                                                                                               ",
   "xxx    o                                 xxxx                                                                      ",
   "xxx   xxx                              x x =x x                                                                   ",
   "xxx                 q                  x x= x x                                                                   ",
   "xxx                 xxx                x x =x x                                                                   ",
   "xxx           o                        x x= x x                                                                   ",
   "xxx          xxx                       x x =x x         !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!           ",
   "xxx                                    x x= x x         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           ",
   "xxx                                    x x =x x         v  xxxv  vxx v   vxxxxxv       vxx    v  v   v            ",
   "xxx=                                   x x= x x            v      vv       v v           v                     o  ",
   "xxx                                   =x x =x x                                                                o  ",
   "xxx=                                   x x= x x                                                                o  ",
   "xxx                                   =x x =x x                                                 o            xxxxx",
   "xxx=                                   x x= x x                                                 xx     xx        x",
   "xxx                                   =x x =x x                                                                  x",
   "xxx=                                   x x= x x                                                     o            x",
   "xxx                                   =x x =x x                                              o     xx            x",
   "xxx=                                   x x                      o      xx                   xx                   x",
   "xxx                                   =x x   o         eee     xx                     xx                         x",
   "xxx=                                   x x  xxx       =xxx     vv          o   xx                                x",
   "xxx                                   =x x   v         vvv                 xx                                    x",
   "xxx=                                   x x                                                                       x",
   "xxx                                   =x x        o                                                              x",
   "xxx                                              xxx                                                             x",
   "xxx                                    r                                                                         x",
   "xxx                                    xxxx                                                                      x",
   "xxx=                                     =x                                                                      x",
   "xxx=                                     =x                                                                      x",
   "xxx=                                     =x                                                                      x",
   "xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
 
 
  ["                                                                             ",
   "                                                                             ",     
   "                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "      @                                                                      ",
   "      e     e                                                                ",
   "      x     x  xxxxxx  x     x    x     x  x   x    x  !                     ",
   "       x   x   x=   x  x    =x    x     x  x  x x   x  !                     ",
   "        x x    x   =x  x=    x    x  x  x  x  x x   x  !                     ",
   "         x     x=   x  x    =x    x  x  x  x  x  x  x  !                     ",
   "         x     x   =x  x=    x    x x x x  x  x   x x  !                     ",
   "         x     x=   x  x    =x    xx   xx  x  x   x x                        ",
   "         x     xxxxxx  xxxxxxx    x     x  x  x    x   !                     ",
   "                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "                                                                             ",
   "                                                                             "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
